name: Deploy Docker Image

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'epic/**'

jobs:
  build-and-deploy:
    uses: valitydev/java-workflow/.github/workflows/maven-service-deploy.yml@v3.0.7
    with:
      ignore-coverage: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      mm-webhook-url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
